version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: loto
      POSTGRES_PASSWORD: loto
      POSTGRES_DB: loto
    ports:
      - "5432:5432"
    volumes:
      - loto_pg:/var/lib/postgresql/data
volumes:
  loto_pg:
